package pocketknife.internal.codegen;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

public class BaseGenerator {

    protected final TypeUtil typeUtil;

    public BaseGenerator(TypeUtil typeUtil) {
        this.typeUtil = typeUtil;
    }

    protected String getGeneratedComment(Class<? extends BaseGenerator> generator) {
        return String.format("Generated by %1$s on %2$s - DO NOT MODIFY\n", generator.getSimpleName(),
                new SimpleDateFormat("yyyy-MM-dd'T'HH:mmZ", Locale.getDefault()).format(new Date()));
    }

}
